/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_lowapple_lowplayer_NDK */

#ifndef _Included_io_lowapple_lowplayer_NDK
#define _Included_io_lowapple_lowplayer_NDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_lowapple_lowplayer_NDK
 * Method:    scanning
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_lowapple_lowplayer_NDK_scanning
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
